spring.application.name=backend

#spring.datasource.url=jdbc:mysql://localhost:3306/matchguard?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8

# Supabase Transaction Pooler (Port 6543)
spring.datasource.url=${datasource_url}
spring.datasource.username=${datasource_username}
#spring.datasource.password=matchguard@visionai.com
spring.datasource.password=${datasource_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



ai.api.key=dummy-api-key-for-development

jwt.secret=${jwt_secret}
jwt.expiration=86400000

# OpenRouter Base Configuration
spring.ai.openai.api-key=${api_key:your-key-from-env-file}
spring.ai.openai.base-url=https://openrouter.ai/api/v1

# Chat Model
spring.ai.openai.chat.options.model=openai/gpt-3.5-turbo
#spring.ai.openai.chat.options.model=openai/gpt-4o-mini

# Cloudflare R2 Configuration
r2.endpoint=${endpoint}
r2.access-key=${access_key}
r2.secret-key=${secret_key}
r2.bucket-name=video-storage
r2.public-cdn-url=https://pub-<HASH>.r2.dev
r2.public-url=${public_url}


# Customizing Swagger UI path (optional)
springdoc.swagger-ui.path=/swagger-ui.html

# API Metadata info
springdoc.api-docs.path=/v3/api-docs
info.app.name=MatchGuard API
info.app.description=Backend API documentation for MatchGuard platform
info.app.version=1.0.0

